In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("clean_student_dataset.csv")

In [4]:
df.head()

,student_id,name,age,city,course,daily_study_hours,attendance_percent,exam_score,enrollment_date,performance_level,study_efficiency
0,1,Henry_LY,22,Delhi,Data Science,6.89,97,73,2025-06-24,Good,10.595065
1,2,Eva_TV,18,Bangalore,Cyber Security,2.77,91,46,2025-06-12,Average,16.606498
2,3,Jack_RH,25,Hyderabad,Machine Learning,9.73,74,100,2025-10-28,Excellent,10.277492
3,4,Charlie_QC,18,Kolkata,Data Science,4.63,82,50,2025-12-02,Average,10.799136
4,5,Grace_WU,24,Pune,Data Science,1.94,71,5,2025-05-25,Poor,2.577320

In [5]:
X=df.drop(columns=["student_id","name","city","course","enrollment_date","performance_level","study_efficiency"])
X

     age  daily_study_hours  attendance_percent  exam_score
0     22               6.89                  97          73
1     18               2.77                  91          46
2     25               9.73                  74         100
3     18               4.63                  82          50
4     24               1.94                  71           5
..   ...                ...                 ...         ...
379   24               3.38                  83          55
380   29               8.70                  76          72
381   25               1.09                  81          36
382   30               4.79                  86          73
383   26               7.14                  97          77

[384 rows x 4 columns]

In [6]:
X=np.array(X)

In [7]:
def qr(X):
    m=len(X)
    n=len(X[0])
    R=np.eye(n)
    Q=[]
    for i in range(m):
        row=[]
        for j in range(n):
            row.append(0.0)
        Q.append(row)

    for j in range(n):
        v=[]
        for i in range(m):
            v.append(X[i][j])
        for k in range(j):
            dot=0
            for i in range(m):
                dot+=Q[i][k]*X[i][j]
            for i in range(m):
                v[i]-=dot*Q[i][k]
        l=0
        for i in range(m):
            l+=v[i]*v[i]
        l=l**0.5
        if abs(l)<1e-9:
            raise ValueError("can't divide by 0")
        for i in range(m):
            Q[i][j]=v[i]/l

    Q=np.array(Q)
    X=np.array(X)
    R=Q.T@X
    return Q,R

In [8]:
qr(X)

(array([[ 0.04547542,  0.04119662,  0.0656002 , -0.00872915],
        [ 0.03720716, -0.02259876,  0.10249945,  0.02879156],
        [ 0.05167661,  0.08413387, -0.05478509,  0.03476628],
        ...,
        [ 0.05167661, -0.08553116, -0.00309118,  0.04854187],
        [ 0.06201193, -0.03426082, -0.05303636,  0.08171843],
        [ 0.05374368,  0.02899621,  0.02078917, -0.00154167]],
       shape=(384, 4)),
 array([[ 4.83777842e+02,  1.05377997e+02,  1.66503492e+03,
          1.19829589e+03],
        [-2.33146835e-13,  5.09238699e+01,  4.83375465e+01,
          4.08001180e+02],
        [-1.73194792e-12, -2.23154828e-13,  2.94061550e+02,
          5.09237587e+01],
        [ 4.10604883e-12,  9.29756272e-13,  1.88196125e-11,
          1.88092436e+02]]))

In [9]:
Q,R=qr(X)
A=Q.T@Q
np.round(A,5)

array([[ 1., -0., -0.,  0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [21]:
x=Q@R
x
def frob(x):
    m=len(x)
    n=len(x[0])

    sum=0
    for i in range(m):
        for j in range(n):
            sum+=(X[i][j]-x[i][j])**2
    return sum**0.5
print(frob(x))

2.3162214856214205e-11

In [11]:
def eig(x,itr=100):
    n=len(x)
    v=np.eye(n)
    x=np.array(x)
    X=x.astype(float).copy()

    for _ in range(itr):
        Q,R=qr(X)
        X=R@Q
        v=v@Q
    return np.diag(X),v

In [12]:
df2=pd.read_csv("student_performance_dataset.csv")
df2.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

In [13]:
Y=df2.drop(columns=["student_id","gender","parental_education","internet_access","extracurricular_activities","part_time_job","final_grade"])
Y

,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
0,4.0,98.0,6.5,76.9,100.0
1,6.3,100.0,5.7,75.5,100.0
2,4.9,85.3,7.9,88.5,97.3
3,2.6,77.5,8.0,85.1,83.8
4,2.2,89.6,4.6,61.8,68.3
...,...,...,...,...,...
995,2.8,75.4,8.2,60.5,70.7
996,6.7,88.4,7.1,82.2,99.5
997,2.6,84.5,8.0,65.2,79.2
998,4.6,85.3,8.1,52.2,82.2
999,3.9,77.4,6.1,45.4,70.4

In [27]:
def svd(A):
    A = np.array(A, dtype=float)
    m, n = A.shape

    # 1. Form B = A transpose A
    B = A.T @ A

    # 2. Find eigenvalues and eigenvectors
    raw_evals, eigvecs = eig(B)
    raw_evals = np.clip(raw_evals, 0, None)

    # 3. Sort eigenvalues and eigenvectors together
    sorted_indices = np.argsort(raw_evals)[::-1]
    evals = raw_evals[sorted_indices]
    V = eigvecs[:, sorted_indices]

    # 4. Singular values
    singular_values = np.sqrt(evals)

    sigma = np.zeros( ( min(m, n), min(m, n) ) )
    for i in range(min(m, n)):
        sigma[i, i] = singular_values[i]

    # 5. Calculate U columns
    U = np.zeros((m, n))

    for i in range(n):
        if singular_values[i] > 1e-8:
            U[:, i] = (A @ V[:, i]) / singular_values[i]

    return U, sigma, V.T

In [28]:
svd(Y)

(array([[ 0.03637773,  0.00848776, -0.01683642,  0.02835303,  0.03116977],
        [ 0.03650044,  0.01498016, -0.01610205,  0.06395741, -0.02808008],
        [ 0.03558928, -0.03843592, -0.01641127, -0.00766769, -0.01914146],
        ...,
        [ 0.03029468,  0.00944193,  0.0068856 , -0.03863654,  0.00730803],
        [ 0.02933591,  0.03907138, -0.02172571, -0.03171229, -0.02584602],
        [ 0.02580144,  0.03940606, -0.00890172, -0.00288556, -0.01827288]],
       shape=(1000, 5)),
 array([[4393.7573659 ,    0.        ,    0.        ,    0.        ,
            0.        ],
        [   0.        ,  362.22519564,    0.        ,    0.        ,
            0.        ],
        [   0.        ,    0.        ,  243.19928773,    0.        ,
            0.        ],
        [   0.        ,    0.        ,    0.        ,   41.15231338,
            0.        ],
        [   0.        ,    0.        ,    0.        ,    0.        ,
           33.28814759]]),
 array([[ 0.02582872,  0.61331751,  0.04880501,  0.50559229,  0.60429216],
        [ 0.01099997,  0.62377158,  0.01833231, -0.78109567,  0.01847963],
        [-0.12367505,  0.48175834, -0.01156569,  0.3640844 , -0.78735136],
        [ 0.27461942,  0.04463522, -0.96034388,  0.01711979,  0.00619787],
        [-0.95315294, -0.02583123, -0.27365646, -0.03762246,  0.1205359 ]]))

In [29]:
U,s,V=svd(Y)
y=U@s@V
y

array([[  4. ,  98. ,   6.5,  76.9, 100. ],
       [  6.3, 100. ,   5.7,  75.5, 100. ],
       [  4.9,  85.3,   7.9,  88.5,  97.3],
       ...,
       [  2.6,  84.5,   8. ,  65.2,  79.2],
       [  4.6,  85.3,   8.1,  52.2,  82.2],
       [  3.9,  77.4,   6.1,  45.4,  70.4]], shape=(1000, 5))

In [30]:
U, s, Vt = svd(Y)

y = U @ s @ Vt

error = np.sqrt(np.sum((Y - y) ** 2))

print("Frobenius error:", error)

Frobenius error: 1.3723061299950711e-08

In [31]:
U, s, V = svd(Y)

print("Y:", Y.shape)
print("U:", U.shape)
print("s:", s.shape)
print("V:", V.shape)

Y: (1000, 5)
U: (1000, 5)
s: (5, 5)
V: (5, 5)